<<<<<<< Updated upstream
# Generated by Django 4.2.6 on 2023-11-07 15:59
=======
# Generated by Django 4.1.1 on 2023-11-06 01:52
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom', '0001_initial'),
>>>>>>> Stashed changes
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Is Urgent?')),
                ('routine', models.CharField(blank=True, max_length=100, null=True)),
                ('em_parts', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('budget_limite', models.CharField(blank=True, max_length=100, null=True)),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrdercreatedby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderdeletedby', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderdonor', to='custom.donor')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderemployee', to='employee.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderupdatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1-Data_Purchase-Request_Purchase-Order',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequestOrderAprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Review', 'Review'), ('Acepted', 'Acepted'), ('Rejected', 'Rejected')], max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderAprovecreatedby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderAprovedeletedby', to=settings.AUTH_USER_MODEL)),
                ('employeeuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderAproveuser', to='employee.employeeuser')),
                ('request_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderAproverequestorder', to='purchase_request.requestorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrderAproveupdatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1-Data-Purchase_Request-Request_Order_Aprove',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('is_delivery', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('Aproved', 'Aproved'), ('Rejected', 'Rejected'), ('Pendende', 'Pendende')], max_length=30, null=True)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemRequestcreatedby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemRequestdeletedby', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemRequestlevel', to='custom.level')),
                ('request_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemRequestrequestorder', to='purchase_request.requestorder')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemRequestrequestunit', to='custom.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItemRequestupdatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1-Data_Purchase-Request_Item-Request',
            },
            managers=[
                ('default_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
